package org.apache.nifi.processors.daxoperation.bo;

public class CardiacRiskScore {
    public String cardiac_id;
    public String uhid;
    public String patientName;
    public String age;
    public String centerId;
    public String dateOfVisit;
    public String prediction_heartRisk;
    public String prediction_risk;
    public String prediction_score;
    public String prediction_optimal;
    public String bmi;
    public String tobacco;
    public String dyslipidemia;
    public String physicalInactivity;
    public String smoking;
    public String framinghamRisk_risk;
    public String framinghamRisk_score;
    public String framinghamRisk_optimal;
    public String labInvestigationRecommended_completeBloodCount;
    public String labInvestigationRecommended_fastingBloodSugar;
    public String labInvestigationRecommended_lipidProfile;
    public String labInvestigationRecommended_ureaCreatinine;
    public String labInvestigationRecommended_HBA1C;
    public String diagnostic_ecg;
    public String diagnostic_chestXray;
    public String diagnostic_echo;
    public String diagnostic_tmt;
    public String diagnostic_usg_kub;
    public String diagnostic_usg;
    public String diagnostic_cardiacCT;
    public String diagnostic_coronaryAngiography;
    public String department;
    public String urgent;
    public String general_treatment;
    public String treatmentofCAD;
    public String General_advice;
    public String repeat_unit;
    public String repeat_duration;
    public String repeat_comment;
    public String offset;
    public String errors;
    public String correlationId;
    public String responseURL;
    public String gender;
}
