package org.apache.nifi.processors.daxoperation.bo;

public enum Resources {
    TOOL, ALLERGY, DOCTOR, MEDICALCONDITION, HOSPITAL, IMMUNIZATION, INSURANCE, MEDICATION, PROCDEURE, TESTNAME, TPA, ADDRESS, DOCTORVISIT, FAMILYHISTORY, HEALTHCHECK, HOSPITALIZATION , 
    LABTEST, MEDICALFILE, PRESCRIPTION, RESTRICTION, PROFILE, DIETPLAN, HOMEHEALTH, SLEEPPATTERN, DIARYDETAILS, UPLOADFILE, RISK_SCORE, MESSAGES, PROCEDURE
}
